### ISSUE TITLE
Dimensional Axes with TimeTypes

### ISSUE THREAD

**Issue by GordStephen** [mbauman/AxisArrays.jl#22]
I've been thinking about building a range-based n-dimensional time-series data structure (similar in functionality to TimeSeries.jl, with the first axis dimensional and any others categorical) on top of AxisArrays.jl - `TimeType`s like `Date`, `DateTime`, and `ZonedDateTime` don't have a defined zero value, however (see https://github.com/JuliaLang/julia/issues/10450), which prevents them from being used as dimensional variables (because of the [current implementation](https://github.com/mbauman/AxisArrays.jl/blob/4332c9e0e09ee91822e0e0828cb33ecfa9d580e1/src/core.jl#L319) of the monitonically-increasing / positive step check).

Would any of these solutions make sense?

1. A more general check that supports `TimeType`s
2. A special case of the check for dimensional axes of type `Range{T}` with `T <: TimeType`
2. A custom axis type for holding `TimeType`s

While I'm still getting my bearings with the package, I'd be happy to either contribute here or add extensions via the downstream package as appropriate.

**Comment by mbauman** [comment]
Welcome!

It's been a while since I've worked on this, but I think that line can be removed completely, allowing ranges to fall back to the generic method on the following line.  I had originally asserted that dimensional axes needed to be strictly increasing (with no duplicates), but that was later relaxed.  This is a relic from the previous design.

**Comment by GordStephen** [comment]
That works great, thanks! I'll submit a PR to change that and fix some deprecation errors as well.
